node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "d1-demo-prod-db"
database_id = "1d30d7f4-2e44-4445-8e65-a96d2cd6025e"
preview_database_id = "DB"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB"
database_name = "d1-demo-preview-db"
database_id = "7f4a5929-357b-41a4-8187-da1b5a86c5f7"